function export2vtu(file,c4n,n4e,p_p1,u_p1,p_p0,u_p0)
[nC,d] = size(c4n); nE = size(n4e,1); type = d^2+1;
if d == 2
    c4n = [c4n,zeros(nC,1)]; 
    u_p1 = [u_p1(1:2:2*nC),u_p1(2:2:2*nC),zeros(nC,1)]; 
    u_p0 = [u_p0(1:2:2*nE),u_p0(2:2:2*nE),zeros(nE,1)];    
end
fid = fopen([file '.vtu'],'wt');
fprintf(fid,'<?xml version="1.0"?>\n');
fprintf(fid,'<VTKFile type="UnstructuredGrid" version="0.1">\n');
fprintf(fid,'<UnstructuredGrid>\n');
fprintf(fid,'<Piece NumberOfPoints="%d"',nC);
fprintf(fid,' NumberOfCells="%d">\n',nE);
fprintf(fid,'<PointData>\n');      
fprintf(fid,'<DataArray type="Float32" Name="p_p1">\n');
fprintf(fid,'%3.3f\n',p_p1);
fprintf(fid,'</DataArray>\n');
fprintf(fid,'<DataArray type="Float32" Name="u_p1"');
fprintf(fid,' NumberOfComponents="3">\n');
fprintf(fid,'%3.3f\n',u_p1');
fprintf(fid,'</DataArray>\n');
fprintf(fid,'</PointData>\n');
fprintf(fid,'<CellData>\n');      
fprintf(fid,'<DataArray type="Float32" Name="p_p0">\n');
fprintf(fid,'%3.3f\n',p_p0);
fprintf(fid,'</DataArray>\n');
fprintf(fid,'<DataArray type="Float32" Name="u_p0"');
fprintf(fid,' NumberOfComponents="3">\n');
fprintf(fid,'%3.3f\n',u_p0');
fprintf(fid,'</DataArray>\n');
fprintf(fid,'</CellData>\n');
fprintf(fid,'<Points>\n');
fprintf(fid,'<DataArray type="Float32" NumberOfComponents="3">\n');
fprintf(fid,'%3.3f\n',c4n');
fprintf(fid,'</DataArray>\n');
fprintf(fid,'</Points>\n');
fprintf(fid,'<Cells>\n');
fprintf(fid,'<DataArray type="Int32" Name="connectivity">\n');
fprintf(fid,'%d\n',(n4e-1)');
fprintf(fid,'</DataArray>\n');
fprintf(fid,'<DataArray type="Int32" Name="offsets">\n');
fprintf(fid,'%d\n',d+1:d+1:(d+1)*nE);
fprintf(fid,'</DataArray>\n');
fprintf(fid,'<DataArray type="UInt8" Name="types">\n');
fprintf(fid,'%d\n',type*ones(nE,1));
fprintf(fid,'</DataArray>\n');
fprintf(fid,'</Cells>\n');
fprintf(fid,'</Piece>\n');
fprintf(fid,'</UnstructuredGrid>\n');
fprintf(fid,'</VTKFile>\n');
fclose(fid);
